### ISSUE TITLE
Automate datasources and project config

### ISSUE THREAD

**Issue by twelch** [seasketch/samoa-reports#1]
We need to simplify and speed up publishing/connecting data to reports for the most common use cases (overlay stats).  This is part of a multi-phase approach to speeding up creating and maintaining reports.

Goals
* Easier to add datasets to the project and publish them
* Easier to keep local files (post-prep) and published files (s3 datasets bucket) in sync

### Approach
- Start in a single geoprocessing project (user space).
- Drop the old patchwork of symlinks and hand-curated and copy/pasted scripts to automate bringing datasets into a geoprocessing project and using in client or function.
- Thoughtfully make it work with the existing types used by toolbox functions (DataGroup, DataClass, Metric).  Will likely refactor these types a bit and push back to the geoprocessing library, but not in the first go until it's proven.
- Leave escape hatches for overriding/editing JSON configuration, doing quick and dirty function development, or pasting from other projects.

### ToDo
- [x] Represent entities and store them on disk as JSON, rather than crammed into config.ts with types included. 
 e.g. `datasources.json`, `metrics.json`, `objectives.json`.  Include schema validation.  Must be able to extend types/schema for project specific needs (mpa classification/objectives).
  - [x] Metrics connect to datasources by specifying datasourceId and an optional classKey to draw keyStats from
  - [x] Metrics connect to objectives using an objectiveId at top-level or class-level
- [x] Create `import:data` function and then CLI wrapper that transforms and publishes vector/raster datasets and creates a new Datasource.
  - [x] vector support
  - [x] raster support
- [x] Create `reimport:data` function that takes the datasource config as-is and reruns data prep, and re-publishes updated datasets.
  - [x] vector support
  - [x] raster support
- [x] Create ProjectClient that weaves together Datasources, MetricGroups, DataClasses, Objectives etc. from disk and validates and makes available to clients and functions with strong typing.
  - [x] Output legacy MetricGroup objects for use by UI components like ClassTable which still use the MetricGroup supported by gp.  This will need to be migrated once gp adds support for new.

- [ ] gdal/ogr commands should be run in workspace container, don't assume that the user has them installed locally.  Should run docker command with param to load volumes for scripts, src data path and dest data path.  AWS credentials may not be needed, can run those commands on the host OS.
- [ ] Create `add:metric`, `add:objective` functions, and then CLI command wrappers.

### Test Plan

- [x] Create a client and function that use the new ConfigClient to access datasources, metricGroup, and precalc stats.  Deploy successfully and test integration with SeaSketch project.
- [x] Ensure objectives are linked and displayed properly.
  - [x] multi-datasource with single top-level objective each.
  - [x] single datasource with multiple classes, one objective per class.
  - [x] raster support
  - [x] vector support
- [ ] Write unit tests that generate test vector and raster data

### Migrating to Geoprocessing

Follow-on to migrate new functionality back to geoprocessing project
- [ ] add encoding package dependency (geoblaze is not finding it)
- [ ] Migrate to use of new zod types, including new MetricGroup schema
- [ ] import and reimport commands runnable from example project
